[AT-Factory-Tool] Support logging and small fixes.
Logs are now output to log files. Logs would be created under LOG_DIR
with the time stamp when the log is created as file name. There would at
most LOG_FILE_NUMBER log files. Each log file size would be less than
log_size/log_file_number. If the total size is larger than LOG_SIZE, the
oldest log file would be deleted.
Log entry format would be as following:
'[<date> <time>] <log_level>/<tag>: <message>'
Valid values for <log_level> are I (INFO), W (WARNING), E (ERROR) and
D (DEBUG).
Valid values for <tag> are
OpStart: Operation start message.
OpSucceed: OPeration succeed message.
OpException: Operation failed message.
Program: Program start/end message.
Autoprov: Auto provision mode start/end message.
For example:
'[2017-11-11 11:11:11] I/Opstart: {TEST_SERIAL at location: 1} Operation
Start'
Also change the reboot logic so that the rebooting device would not
disappear from the device list, instead it would have a status
rebooting.
The product attribute file extension is changed to '*.atpa' to fit the
file extension from development console. After this commit, all old
test product attribute file WOULD NOT BE COMPATIBLE without changing
extension.
Better handle situation when there's no more keys left in the ATFA.

Change-Id: I4dd0d1d03befd9ba1566c87a884bd3a379c3d4ba

Test: Unit tests and manual test.

Bug: b/69630963, b/68662614, b/65997445